version: '3'
services:
  api-server:
    image: api-server
    build: ./server
    env_file: ./server/.env
    ports:
      - '5000:5000'
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules

networks:
  mern-app:
    driver: bridge
